[workspace]
members = [
    "modelone",
    "uione",
    "uilang",
    "uilang_test",
    "test1",
]

# https://doc.rust-lang.org/nightly/cargo/reference/profiles.html#overrides
[profile.dev.package."*"]
opt-level = 3
